# Generated by Django 4.2.7 on 2023-11-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(max_length=255, upload_to='documents/'),
        ),
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_document_file', models.FileField(max_length=255, upload_to='processed_documents/')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_document_relation', to='UploadService.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='processed_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_document', to='UploadService.processeddocument'),
        ),
    ]
